# Generated by Django 4.1.4 on 2023-03-02 19:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_adjectivechange_date_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastPullDate', models.DateTimeField(default=datetime.datetime(2000, 5, 12, 0, 0))),
                ('userId', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastPull', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
