# Generated by Django 4.1.4 on 2023-03-04 11:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_date_modified_adjectivechange_lastmodifieddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeze',
            name='extensionDecisionId',
        ),
        migrations.AddField(
            model_name='adjectivechange',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='alimonychange',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='certificateofexcellence',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='durationchange',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='extension',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='freeze',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='freeze',
            name='dispatchDecisionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freeze', to='app.dispatch'),
        ),
        migrations.AddField(
            model_name='graduatestudies',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='nomination',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='permissions',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='regularization',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='report',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='specializationchange',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='universitychange',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='universitydegree',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
