# Generated by Django 4.1.4 on 2023-08-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_usersynchronization_lastmodifieddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastpull',
            name='lastPullDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersynchronization',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
