# Generated by Django 4.1.4 on 2023-08-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_lastpull_lastpulldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastpull',
            name='lastPullDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
