# Generated by Django 4.1.4 on 2023-08-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_adjectivechange_modifiedbyoffline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='emailSent',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
