# Generated by Django 4.1.4 on 2023-08-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_extension_emailsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='emailSent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
